apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "track-all-curl-connections"
spec:
  kprobes:
  - call: "tcp_connect"
    syscall: false
    args:
    - index: 0
      type: "sock"
    selectors:
    - matchBinaries:
      - operator: "In"
        values:
        - "/usr/bin/curl"