apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: troubleshooter-ncat-dig
  namespace: default
  labels:
    k8s-app: troubleshooter-ncat-dig
spec:
  selector:
    matchLabels:
      name: troubleshooter-ncat-dig
  template:
    metadata:
      labels:
        name: troubleshooter-ncat-dig
    spec:
      dnsPolicy: "ClusterFirst"
      containers:
      - name: dig
        image: nicolaka/netshoot
        command: ["/bin/sh", "-c", "--"]
        args: ["while true; do dig sr.se | grep time; sleep 60; done"]
      - name: ncat
        image: itsthenetwork/alpine-ncat:latest
        command: ["/bin/sh", "-c", "--"]
        args: ['while true; do ncat -v -z sr.se 443 2>&1 | sed -n "3 s/.*in \(.* seconds\)\./\1/p"; sleep 60; done']
