apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: troubleshooter-ncat-dig
  namespace: default
  labels:
    k8s-app: troubleshooter-ncat-dig
spec:
  selector:
    matchLabels:
      name: troubleshooter-ncat-dig
  template:
    metadata:
      labels:
        name: troubleshooter-ncat-dig
    spec:
      dnsPolicy: "ClusterFirst"
      containers:
      - name: dig
        image: nicolaka/netshoot
        command: ["/bin/sh", "-c", "--"]
        args: ['echo "This pod tests the DNS resolution time:" && while true; do dig one.one.one.one | grep time; sleep 60; done']
      - name: ncat-direct
        image: itsthenetwork/alpine-ncat:latest
        command: ["/bin/sh", "-c", "--"]
        args: ['echo "This pod tests the tcp connection with the IP address:" && while true; do ncat -v -z 1.1.1.1 443 2>&1 | sed -n "3 s/.*in \(.* seconds\)\./\1/p"; sleep 60; done']
      - name: ncat-dns
        image: itsthenetwork/alpine-ncat:latest
        command: ["/bin/sh", "-c", "--"]
        args: ['echo "This pod tests the tcp connection with the hostname:" && while true; do ncat -v -z one.one.one.one 443 2>&1 | sed -n "3 s/.*in \(.* seconds\)\./\1/p"; sleep 60; done']
